# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db019fa91ad798a6577c31f9c4825ee2a43ce74a749897480269f47eaf08970433297d79465953af43b58905e6804d97678359ea62228ef673825a756c7d46ee

test:
  secret_key_base: 31fd50c82586d742d3998948ffe73b309ebd4bc83643e34374e0a33ecdc135b784fc749b0ae545daee53e69825a9b0f7cc498d8ce86f6f7ccada65da1757e7d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
